name: Build and Deploy Docs

on:
  push:
    branches:
    - main    # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Install manim dependencies on Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install build-essential python3-dev libcairo2-dev libpango1.0-dev pybtex python-pybtex-doc python3-pybtex
      
    - name: Install pybtex
      run: |
        pip install pybtex

    - name: Install this package
      run: |
        pip install -e .

    - name: Check pybtex installation
      run: |
        pip list | grep pybtex


    - name: Build docs
      run: |
        uv venv
        uv sync --frozen --extra docs
        source .venv/bin/activate
        cd docs
        make clean html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
